/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * Azure Functions OpenAPI Extension
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import * as url from "url";
import * as portableFetch from "portable-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "http://localhost:7071/api".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = portableFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name: "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface InboundDto
 */
export interface InboundDto {
    /**
     * 
     * @type {number}
     * @memberof InboundDto
     */
    intValue?: number;
    /**
     * 
     * @type {string}
     * @memberof InboundDto
     */
    stringValue?: string;
    /**
     * 
     * @type {number}
     * @memberof InboundDto
     */
    floatValue?: number;
}


/**
 * NameApi - fetch parameter creator
 * @export
 */
export const NameApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {InboundDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        run(body?: InboundDto, options: any = {}): FetchArgs {
            const localVarPath = `/Function1`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"InboundDto" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * NameApi - functional programming interface
 * @export
 */
export const NameApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {InboundDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        run(body?: InboundDto, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<string> {
            const localVarFetchArgs = NameApiFetchParamCreator(configuration).run(body, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * NameApi - factory interface
 * @export
 */
export const NameApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @param {InboundDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        run(body?: InboundDto, options?: any) {
            return NameApiFp(configuration).run(body, options)(fetch, basePath);
        },
    };
};

/**
 * NameApi - object-oriented interface
 * @export
 * @class NameApi
 * @extends {BaseAPI}
 */
export class NameApi extends BaseAPI {
    /**
     * 
     * @param {InboundDto} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NameApi
     */
    public run(body?: InboundDto, options?: any) {
        return NameApiFp(this.configuration).run(body, options)(this.fetch, this.basePath);
    }

}

